### ISSUE TITLE
部分操作导致 app 奔溃，相关错误：java.lang.IllegalArgumentException: Detected multithreaded access to SnapshotStateObserver

### ISSUE THREAD

**Issue by zqhong** [aaa1115910/bv#131]
### Bug 描述

错误日志：
```
--------- beginning of crash
05-29 13:24:03.322  5746  5746 E AndroidRuntime: FATAL EXCEPTION: main
05-29 13:24:03.322  5746  5746 E AndroidRuntime: Process: dev.aaa1115910.bv, PID: 5746
05-29 13:24:03.322  5746  5746 E AndroidRuntime: java.lang.IllegalArgumentException: Detected multithreaded access to SnapshotStateObserver: previousThreadId=1086), currentThread={id=2, name=main}. Note that observation on multiple threads in layout/draw is not supported. Make sure your measure/layout/draw for each Owner (AndroidComposeView) is executed on the same thread.
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at R.d.a0(SourceFile:3)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at b0.v.c(SourceFile:113)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at C0.o0.a(SourceFile:3)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at C0.H.o(SourceFile:51)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at Q3.v2.g(SourceFile:112)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.b(SourceFile:40)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.b(SourceFile:48)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.b(SourceFile:48)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.b(SourceFile:48)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.b(SourceFile:48)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.b(SourceFile:48)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.o(SourceFile:15)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.g(SourceFile:27)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at J0.l.h(SourceFile:17)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.T.q(SourceFile:282)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.T.q(SourceFile:299)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.T.q(SourceFile:299)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.T.p(SourceFile:62)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.M.u(SourceFile:19)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.M.H(SourceFile:35)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.M.o(SourceFile:24)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at D0.l.run(SourceFile:1337)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:967)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:249)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8087)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
05-29 13:24:03.322  5746  5746 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1188)
05-29 13:24:03.323  5746  5746 E LogCatcher: ======== UncaughtException ========
05-29 13:24:03.323  5746  5746 E LogCatcher: java.lang.IllegalArgumentException: Detected multithreaded access to SnapshotStateObserver: previousThreadId=1086), currentThread={id=2, name=main}. Note that observation on multiple threads in layout/draw is not supported. Make sure your measure/layout/draw for each Owner (AndroidComposeView) is executed on the same thread.
05-29 13:24:03.323  5746  5746 E LogCatcher:  at R.d.a0(SourceFile:3)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at b0.v.c(SourceFile:113)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at C0.o0.a(SourceFile:3)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at C0.H.o(SourceFile:51)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at Q3.v2.g(SourceFile:112)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.b(SourceFile:40)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.b(SourceFile:48)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.b(SourceFile:48)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.b(SourceFile:48)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.b(SourceFile:48)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.b(SourceFile:48)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.o(SourceFile:15)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.g(SourceFile:27)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at J0.l.h(SourceFile:17)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.T.q(SourceFile:282)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.T.q(SourceFile:299)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.T.q(SourceFile:299)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.T.p(SourceFile:62)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.M.u(SourceFile:19)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.M.H(SourceFile:35)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.M.o(SourceFile:24)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at D0.l.run(SourceFile:1337)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at android.os.Handler.handleCallback(Handler.java:967)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at android.os.Handler.dispatchMessage(Handler.java:104)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at android.os.Looper.loop(Looper.java:249)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at android.app.ActivityThread.main(ActivityThread.java:8087)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at java.lang.reflect.Method.invoke(Native Method)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
05-29 13:24:03.323  5746  5746 E LogCatcher:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1188)

```

### 复现问题的步骤

```plain text
1. 进入设置页面
2. 上下左右点击设置，有概率导致奔溃
```

### 预期行为

不奔溃

### 请确认已更新到以下所示的最新版本

我正在使用旧版本

### 当前版本号

r639.alpha

### Android 版本

Android 11

### 相关日志

[bv-crash.log](https://github.com/aaa1115910/bv/files/15479226/bv-crash.log)

**Comment by zqhong** [comment]
reopen
